# NumPy数组的基础知识


在Python中，数据操作几乎与NumPy数组操作同义：即使是像Pandas这样的新工具（[第3部分](03.00-Introduction-to-Pandas.ipynb)）也建立在NumPy数组之上。

本章将展示几个使用NumPy数组操作的示例，以访问数据和子数组，并对数组进行分割、重塑和连接。

虽然这里展示的操作类型可能显得有些枯燥和学究，但它们构成了书中许多其他示例的基础。

请好好了解这些内容！

我们将在这里涵盖一些基本数组操作的类别：

- *数组属性*：确定数组的大小、形状、内存消耗和数据类型

- *数组索引*：获取和设置单个数组元素的值

- *数组切片*：在较大的数组中获取和设置较小的子阵列

- *重塑阵列*：改变给定阵列的形状

- *连接与拆分阵列*：将多个阵列合并为一个，以及将一个阵列拆分为多个。

## NumPy数组属性：


首先，让我们讨论一些有用的数组属性。

我们将从定义一维、二维和三维的随机数组开始。

我们将使用NumPy的随机数生成器，并用一个固定值对其进行*初始化*，以确保每次运行此代码时生成相同的随机数组。

In [1]:
import numpy as np
rng = np.random.default_rng(seed=1701)  # seed for reproducibility

x1 = rng.integers(10, size=6)  # one-dimensional array
x2 = rng.integers(10, size=(3, 4))  # two-dimensional array
x3 = rng.integers(10, size=(3, 4, 5))  # three-dimensional array

每个数组都有一些属性，包括 `ndim`（维度数量）、`shape`（每个维度的大小）、`size`（数组的总大小）和 `dtype`（每个元素的类型）：

In [2]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:   ", x3.dtype)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype:    int64


更多关于数据类型的讨论，请参见[理解Python中的数据类型](02.01-Understanding-Data-Types.ipynb)。

## 数组索引：访问单个元素


如果您熟悉Python的标准列表索引，那么NumPy中的索引将会显得非常熟悉。

在一维数组中，可以通过在方括号中指定所需的索引来访问第$i^{th}$个值（从零开始计数），这与Python列表的用法相同。

In [3]:
x1

array([9, 4, 0, 3, 8, 6])

In [4]:
x1[0]

np.int64(9)

In [5]:
x1[4]

np.int64(8)

要从数组的末尾进行索引，可以使用负数索引：

In [6]:
x1[-1]

np.int64(6)

In [7]:
x1[-2]

np.int64(8)

在多维数组中，可以使用以逗号分隔的 `(行, 列)` 元组来访问项：

In [8]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [9]:
x2[0, 0]

np.int64(3)

In [10]:
x2[2, 0]

np.int64(0)

In [11]:
x2[2, -1]

np.int64(9)

值也可以使用任何前面的索引表示法进行修改：

In [12]:
x2[0, 0] = 12
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

请注意，与Python列表不同，NumPy数组具有固定类型。

这意味着，例如，如果您尝试将浮点值插入整数数组，该值将被静默截断。请不要对这种行为感到意外！

In [13]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 4, 0, 3, 8, 6])

## 数组切片：访问子数组


正如我们可以使用方括号访问单个数组元素，我们也可以使用带有冒号（`:`）字符的*切片*表示法来访问子数组。

NumPy 的切片语法遵循标准 Python 列表的规则；要访问数组 `x` 的一个切片，可以使用以下格式：

``` python
x[start:stop:step]
```

如果这些参数中的任何一个未指定，则默认为 `start=0`，`stop=<维度大小>`，`step=1`。

接下来，让我们看一些在一维和多维中访问子数组的示例。

### 一维子数组

以下是访问一维子数组中元素的一些示例：

In [14]:
x1

array([3, 4, 0, 3, 8, 6])

In [15]:
x1[:3]  # first three elements

array([3, 4, 0])

In [16]:
x1[3:]  # elements after index 3

array([3, 8, 6])

In [17]:
x1[1:4]  # middle subarray

array([4, 0, 3])

In [18]:
x1[::2]  # every second element

array([3, 0, 8])

In [19]:
x1[1::2]  # every second element, starting at index 1

array([4, 3, 6])

一个可能令人困惑的情况是，当 `step` 值为负时。

在这种情况下，`start` 和 `stop` 的默认值会被交换。

这成为反转数组的一种方便方法：

In [20]:
x1[::-1]  # all elements, reversed

array([6, 8, 3, 0, 4, 3])

In [21]:
x1[4::-2]  # every second element from index 4, reversed

array([8, 0, 3])

### 多维子数组

多维切片的工作方式相同，多个切片之间用逗号分隔。

例如：

In [22]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [23]:
x2[:2, :3]  # first two rows & three columns

array([[12,  1,  3],
       [ 4,  0,  2]])

In [24]:
x2[:3, ::2]  # three rows, every second column

array([[12,  3],
       [ 4,  2],
       [ 0,  6]])

In [25]:
x2[::-1, ::-1]  # all rows & columns, reversed

array([[ 9,  6,  0,  0],
       [ 3,  2,  0,  4],
       [ 7,  3,  1, 12]])

#### 访问数组的行和列

一种常见的操作是访问数组的单个行或列。

这可以通过结合索引和切片来实现，使用一个由单个冒号（`:`）标记的空切片。

In [26]:
x2[:, 0]  # first column of x2

array([12,  4,  0])

In [27]:
x2[0, :]  # first row of x2

array([12,  1,  3,  7])

在行访问的情况下，可以省略空切片，以实现更紧凑的语法：

In [28]:
x2[0]  # equivalent to x2[0, :]

array([12,  1,  3,  7])

### 子数组作为无拷贝视图

与 Python 列表切片不同，NumPy 数组切片返回的是数组数据的 *视图* 而不是 *拷贝*。

请考虑我们之前提到的二维数组：

In [29]:
print(x2)

[[12  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


让我们从中提取一个 $2 \times 2$ 子数组： 


In [30]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  1]
 [ 4  0]]


现在，如果我们修改这个子数组，我们会发现原始数组发生了变化！请注意：

In [31]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  1]
 [ 4  0]]


In [32]:
print(x2)

[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


一些用户可能会对此感到惊讶，但这实际上是有利的：例如，在处理大型数据集时，我们可以访问并处理这些数据集中的部分内容，而无需复制底层数据缓冲区。

### 创建数组的副本

尽管数组视图具有良好的特性，但有时显式地复制数组或子数组中的数据是很有用的。这可以通过 `copy` 方法最简单地实现。

In [33]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  1]
 [ 4  0]]


如果我们现在修改这个子数组，原始数组不会受到影响：

In [34]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  1]
 [ 4  0]]


In [35]:
print(x2)

[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


## 数组的重塑

另一种有用的操作是数组的重塑，这可以通过 `reshape` 方法来实现。

例如，如果您想将数字 1 到 9 放入一个 $3 \times 3$ 的网格中，可以执行以下操作：

In [36]:
grid = np.arange(1, 10).reshape(3, 3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size of the initial array must match the size of the reshaped array, and in most cases the `reshape` method will return a no-copy view of the initial array.

常见的重塑操作是将一维数组转换为二维行或列矩阵。

In [37]:
x = np.array([1, 2, 3])
x.reshape((1, 3))  # row vector via reshape

array([[1, 2, 3]])

In [38]:
x.reshape((3, 1))  # column vector via reshape

array([[1],
       [2],
       [3]])

方便的简写方式是使用 `np.newaxis` 在切片语法中：

In [39]:
x[np.newaxis, :]  # row vector via newaxis

array([[1, 2, 3]])

In [40]:
x[:, np.newaxis]  # column vector via newaxis

array([[1],
       [2],
       [3]])

这是我们在本书剩余部分中将经常使用的一种模式。

## 数组连接与拆分

前述所有例程均针对单个数组进行操作。NumPy 还提供了将多个数组合并为一个的工具，并可以将单个数组拆分为多个数组。

### 数组的连接

在NumPy中，数组的连接或合并主要通过`np.concatenate`、`np.vstack`和`np.hstack`这几种方法来实现。

`np.concatenate`将一个元组或数组列表作为其第一个参数，如下所示：

In [41]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

您还可以一次连接多个数组：

In [42]:
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


它可以用于二维数组：

In [43]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [44]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [45]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

对于处理混合维度的数组，使用 `np.vstack`（垂直堆叠）和 `np.hstack`（水平堆叠）函数会更加清晰。

In [46]:
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [47]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

同样，对于高维数组，`np.dstack` 将沿着第三个轴堆叠数组。

### 数组的拆分

连接的反义词是拆分，这可以通过函数 `np.split`、`np.hsplit` 和 `np.vsplit` 来实现。对于每个函数，我们可以传递一个包含拆分点的索引列表。

In [48]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


注意，*N* 个分割点会导致 *N* + 1 个子数组。

相关的函数 `np.hsplit` 和 `np.vsplit` 是相似的：

In [49]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [51]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


同样，对于高维数组，`np.dsplit` 将沿着第三个轴分割数组。